ktor:
    application:
        modules:
            - dev.wo.ApplicationKt.module
    deployment:
        port: "$PORT:8080"

logging:
    level:
        root: "$LOG_LEVEL:INFO"

app:
    profile: "$PROFILE:default"

rabbitmq:
    host: "$RABBITMQ_HOST:localhost"
    port: "$RABBITMQ_PORT:5672"
    user: "$RABBITMQ_DEFAULT_USER:guest"
    password: "$RABBITMQ_DEFAULT_PASS:guest"