ktor:
    application:
        modules:
            - dev.wo.ApplicationKt.module
    deployment:
        port: "$PORT:8080"

    logging:
        level:
            "$LOG_LEVEL:INFO"

app:
    profile: "$PROFILE:default"