ktor:
    application:
        modules:
            - dev.wo.ApplicationKt.module
    deployment:
        port: "$PORT:8080"

logging:
    level:
        "$LOG_LEVEL:INFO"
    loggers: INFO

app:
    profile: "$PROFILE:default"