ktor:
    application:
        modules:
            - dev.wo.ApplicationKt.module
    deployment:
        port: "$PORT:8080"

logging:
    level:
        root: "$LOG_LEVEL:INFO"

app:
    profile: "$PROFILE:default"