global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ffp_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['parser-api:8080']
  - job_name: 'ffp_api_prod'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ffp.woservices.com.br']